// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Data;

#nullable disable

namespace Website.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    [Migration("20220826184719_DiscordRolesSeparated")]
    partial class DiscordRolesSeparated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Website.Data.User", b =>
                {
                    b.Property<int>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong?>("DiscordSnowflake")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("LastControlTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastPilotTime")
                        .HasColumnType("datetime");

                    b.HasKey("Vid");

                    b.HasIndex("DiscordSnowflake");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Website.Data.UserRole", b =>
                {
                    b.Property<ulong>("Snowflake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Roles")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Snowflake");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Website.Data.User", b =>
                {
                    b.HasOne("Website.Data.UserRole", "Discord")
                        .WithMany()
                        .HasForeignKey("DiscordSnowflake");

                    b.Navigation("Discord");
                });
#pragma warning restore 612, 618
        }
    }
}
