name: Build On Push
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: |
        rm -rf publish
        git clone -b deploy https://github.com/ivao-xa/website publish
        rm -rf publish/*
        dotnet build --configuration DEBUG Website/Website.csproj -o publish
    - name: Commit
      run: |
        cd publish
        git config advice.addIgnoredFile false
        git config --global user.name 'Autobuild'
        git config --global user.email 'xa-wm@ivao.aero'
        git add * || true
        git commit -m "Automated build of ${{ github.sha }}"
        git push --force